source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target :RxSwiftDemo do
    platform :ios, '8.0'
    
    pod 'SnapKit', '~> 4.0.0'
    pod 'Kingfisher', '~> 4.0'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
end
